#!/bin/bash
set -e

# ./init_ca.sh Fleet AU Victoria Melbourne Ophix "Internal Systems"

if [ $# -ne 6 ]; then
    echo "Usage: $0 <CertificateAuthorityName> <C> <ST> <L> <O> <OU>"
    exit 1
fi

CERTAUTH="$1"
C="$2"
ST="$3"
L="$4"
O="$5"
OU="$6"

CA_DIR="${CERTAUTH}-CA"

if [ -e "$CA_DIR" ]; then
    echo "Error: $CA_DIR already exists"
    exit 1
fi

echo "Creating CA structure in $CA_DIR ..."

mkdir -p "$CA_DIR"/{certs,crl,newcerts,private}
chmod 700 "$CA_DIR/private"

touch "$CA_DIR/index.txt"
echo 1000 > "$CA_DIR/serial"
echo 1000 > "$CA_DIR/crlnumber"

# Create OpenSSL config
cat > "$CA_DIR/ca.cnf" <<EOF
[ ca ]
default_ca = CA_default

[ CA_default ]
dir               = ./$CA_DIR
certs             = \$dir/certs
new_certs_dir     = \$dir/newcerts
database          = \$dir/index.txt
serial            = \$dir/serial
crlnumber         = \$dir/crlnumber
crl_dir           = \$dir/crl
private_key       = \$dir/private/ca.key.pem
certificate       = \$dir/certs/ca.cert.pem
default_days      = 365
default_md        = sha256
policy            = policy_loose
x509_extensions   = v3_ca
unique_subject    = no
copy_extensions   = copy

[ policy_loose ]
countryName             = optional
stateOrProvinceName     = optional
localityName            = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

[ req ]
default_bits       = 4096
prompt             = no
default_md         = sha256
distinguished_name = req_distinguished_name
x509_extensions    = v3_ca

[ req_distinguished_name ]
C  = $C
ST = $ST
L  = $L
O  = $O
OU = $OU
CN = $CERTAUTH Internal CA

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true
keyUsage = critical, cRLSign, keyCertSign

[ v3_server ]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer
EOF

echo "Generating CA private key..."
openssl genrsa -out "$CA_DIR/private/ca.key.pem" 4096
chmod 600 "$CA_DIR/private/ca.key.pem"

echo "Generating CA self-signed certificate..."
openssl req -config "$CA_DIR/ca.cnf" \
    -key "$CA_DIR/private/ca.key.pem" \
    -new -x509 -days 3650 -sha256 \
    -out "$CA_DIR/certs/ca.cert.pem"

# Write .env for issue_cert.sh
cat > .env <<EOF
# Auto-generated by init_ca.sh
CA_CONFIG="./$CA_DIR/ca.cnf"

# Default DN fields for issued certs
DN_C="$C"
DN_ST="$ST"
DN_L="$L"
DN_O="$O"
DN_OU="$OU"
EOF

echo
echo "CA initialized successfully!"
echo "CA directory: $CA_DIR"
echo "CA config:    $CA_DIR/ca.cnf"
echo "Wrote config: .env"
echo
echo "You can now run: ./issue_cert.sh create <domain> <host> <ip>"
